
- name: Enable lionheartp/Hyprland COPR repository
  become: yes
  ansible.builtin.command: dnf5 copr enable -y lionheartp/Hyprland
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:lionheartp:Hyprland.repo

- name: Enable awww COPR repository
  become: yes
  ansible.builtin.command: dnf5 copr enable -y scottames/awww
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:scottames:awww.repo

- name: Install core system packages, window manager, and developer tools
  ansible.builtin.dnf5:
    name:
      # Window Manager & Shell Essentials
      - hyprland
      - waybar
      - rofi-wayland
      - mako # Notification Daemon - allows hyprland to display notifications from applications
      - awww # Wallpaper Daemon
      - xdg-desktop-portal-hyprland
      - kitty # Terminal Emulator
      # Clipboard & Screenshots
      - wl-clipboard
      - grim
      - slurp
    state: present

- name: Set Hyprland as default session for user
  become: yes
  ansible.builtin.copy:
    dest: "/var/lib/AccountsService/users/{{ target_user }}"
    content: |
      [User]
      Session=hyprland
      SystemAccount=false
