- name: Enable starship COPR repository
  become: yes
  ansible.builtin.command: dnf5 copr enable -y atim/starship
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:starship.repo

- name: Install eza (better than ls)
  ansible.builtin.dnf5:
    name: eza
    state: present

- name: Install Starship
  ansible.builtin.dnf5:
    name: starship
    state: present

- name: Ensure Zsh is installed
  ansible.builtin.dnf5:
    name: zsh
    state: present

- name: Set Zsh as the default shell for the current user
  become: yes
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh
